spring:
    profiles: ust
    application:
        name: LOCALHOSTUS

server:
    port: 8792

eureka:
    instance:
        appname: LOCALHOSTUS
    client:
        fetchRegistry: true
        serviceUrl:
            defaultZone: 'http://localhost-us:8761/eureka/'
