spring:
    profiles: vnf
    application:
        name: LOCALHOSTVN

server:
    port: 8801

eureka:
    instance:
        appname: LOCALHOSTVN
    client:
        fetchRegistry: true
        serviceUrl:
            defaultZone: 'http://localhost-vn:8763/eureka/'
